hmcts/idam-health-checker

- build.gradle
- src/main/resources/application.yaml
* Check/Freshness intervals.
* Increase version.
* Tidy up dependencies.
> Tidy up + updated version

- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreAuthenticationHealthProbe.java
- src/test/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreAuthenticationHealthProbeTest.java
Keep it up if the test user does not exist.
> Improvements in the UserStore authentication health probe 

- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreAuthenticationHealthProbe.java
- src/test/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreAuthenticationHealthProbeTest.java
Reverts hmcts/idam-health-checker#24
> Revert "Improvements in the UserStore authentication health probe "

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/command/DSReplicationHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreHealthProbeConfiguration.java
https://tools.hmcts.net/jira/browse/SIDM-2673
Introduced a new profile to allow for excluding replication checks for single node clusters.
```
[ ] Yes
[x] No
```
> SIDM-2673: Introduce a "single" profile

- .travis.yml
- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/probe/ScheduledHealthProbeIndicator.java
- src/test/java/uk/gov/hmcts/reform/idam/health/probe/ScheduledHealthProbeIndicatorTest.java
- Checking probe status only when MARK_AS_DOWN otherwise status is ok
- Adding log warn and simplify method complexity
- update lib version
[SIDM-3596](https://tools.hmcts.net/jira/browse/SIDM-3596)
```
[ ] Yes
[x] No
```
> Sidam 3596 bug health check app

- src/main/java/uk/gov/hmcts/reform/idam/health/probe/ScheduledHealthProbeIndicator.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Not warn but info

- README.md
https://tools.hmcts.net/jira/browse/SIDM-n/a
Health Check Readme
Add useful info about the health check.
```
[ ] Yes
[x] No
```
> SIDM-n/a - Health Check Readme

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbeProperties.java
- src/main/java/uk/gov/hmcts/reform/idam/health/command/ReplicationInfo.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbeTest.java
https://tools.hmcts.net/jira/browse/SIDM-3546
Aligned with 6.5. However, this area of code could use some refactor. The delay-threshold config might require a change as well, because I don't know yet what's an acceptable value there and what isn't. 
```
[x] Yes
[ ] No
```
> SIDM-3546 Make the probe work with 6.5.

- src/main/java/uk/gov/hmcts/reform/idam/health/am/AmHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbe.java
- src/test/java/uk/gov/hmcts/reform/idam/health/indicator/HealthCheckTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbeTest.java
https://tools.hmcts.net/jira/browse/SIDM-3692
```
[ ] Yes
[x] No
```
> Fix some of the health checker problems

- build.gradle
> SIDM-3692 Increment the version.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/uk/gov/hmcts/reform/idam/health/am/AmIsAliveHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/am/AmPasswordGrantHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/am/AmProvider.java
- src/main/java/uk/gov/hmcts/reform/idam/health/backup/FileFreshnessProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/idm/IdmPingHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/indicator/HealthCheck.java
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/probe/FixedHealthProbeIndicator.java
- src/main/java/uk/gov/hmcts/reform/idam/health/probe/HealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/probe/HealthProbeIndicator.java
- src/main/java/uk/gov/hmcts/reform/idam/health/probe/ScheduledHealthProbeIndicator.java
- src/main/java/uk/gov/hmcts/reform/idam/health/props/ConfigProperties.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreSearchHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreAuthenticationHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/vault/VaultEnvironmentPostProcessor.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbeTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbeTest.java
https://tools.hmcts.net/jira/browse/SIDM-3692
```
[x] Yes
[ ] No
```
> SIDM-3692 Fix and align with FR 6.5

- README.md
- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/indicator/HealthCheck.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/idam/health/am/AmPasswordGrantHealthProbeTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/command/ReplicationCommandProbeTest.java
https://tools.hmcts.net/jira/browse/SIDM-3692
```
[ ] Yes
[x] No
```
> SIDM-3692 Increment version and disable details.

- .travis.yml
Add extra logging to travis deploy.
```
[ ] Yes
[x] No
```
> Add a flag for debugging Travis builds.

- build.gradle
Fix the final JAR name that gets uploaded to bintray.
```
[ ] Yes
[x] No
```
> Override target jar name.

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/util/LogHelper.java
Fix an incorrect manifest in the file uploaded to Bintray preventing the app from running.
```
[ ] Yes
[x] No
```
> SIDM-3585 Build fixes 1.

- .gitignore
- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapConnectionsHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapQueryHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapWorkQueueHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreHealthProbeProperties.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreHealthProbeProperties.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapConnectionsHealthProbeTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbeTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapWorkQueueHealthProbeTest.java
https://tools.hmcts.net/jira/browse/SIDM-5229
Added LDAP work queue and connection monitors for token store.
```
[ ] Yes
[X] No
```
> SIDM-5229 CTS connections ldap monitor

- .github/workflows/gradle.yml
https://tools.hmcts.net/jira/browse/SIDM-5229 (deployment of)
Add release step to github action
```
[ ] Yes
[X] No
```
> GitHub action

- src/main/java/uk/gov/hmcts/reform/idam/health/info/ForgerockVersionInfoContributor.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/idam/health/info/ForgerockVersionInfoContributorTest.java
https://tools.hmcts.net/jira/browse/SIDM-5689
Add info endpoint to display FR version from file.
```
[ ] Yes
[X] No
```
> add FR info

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/vault/VaultEnvironmentPostProcessor.java
- src/test/java/uk/gov/hmcts/reform/idam/health/ldap/LdapReplicationHealthProbeTest.java
- src/test/java/uk/gov/hmcts/reform/idam/health/vault/VaultEnvironmentPostProcessorTest.java
https://tools.hmcts.net/jira/browse/SIDM-8635
https://tools.hmcts.net/jira/browse/SIDM-8637
Added new secrets.
Updated ldap replication check.
```
[ ] Yes
[X] No
```
> SIDM 8635 new secrets and ldap replication

- build.gradle
- src/main/java/uk/gov/hmcts/reform/idam/health/backup/BackupMonitorHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/backup/BackupMonitorHealthProbeProperties.java
- src/main/java/uk/gov/hmcts/reform/idam/health/backup/FileFreshnessProbe.java
- src/main/java/uk/gov/hmcts/reform/idam/health/tokenstore/TokenStoreHealthProbeConfiguration.java
- src/main/java/uk/gov/hmcts/reform/idam/health/userstore/UserStoreHealthProbeConfiguration.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-8625
Remove incremental backup check and stop replication probes marking as down
```
[ ] Yes
[X] No
```
> Sidm 8625 backups

- build.gradle
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-9177
Change health status order
> SIDM-9177 change status order

- .github/workflows/ado_artifacts_build.yml
- build.gradle
CME-530
Replace jitpack with azure artifactory
> CME-530 replace jitpack with azure
